Override style for button link
OpusCapita/opuscapita-ui pull request #25
Opened 2019-12-20 09:52 UTC by ksafin-sc

https://github.com/OpusCapita/pimline/issues/1015

2019-12-20 10:17 UTC, ashchitlyak-sc requested changes

2019-12-20 10:17 UTC, ashchitlyak-sc commented on src/client/less/opuscapita-theme/buttons.less
> +  &:hover {
```suggestion
  &:focus:hover {
```

2019-12-20 15:43 UTC, eviktorovich-sc approved these changes

2019-12-23 04:57 UTC, ashchitlyak-sc approved these changes

2019-12-26 15:41 UTC, merged